server:
  port: 8081
spring:
  profiles:
    active: dev #默认dev；java -jar xxx.jar --spring.profiles.active=prod 生产环境执行
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 #连接池最大连接数
      minimum-idle: 0 #允许的最小空闲属
      idle-timeout: 180000 #空闲超时是 180000 毫秒，当数据库连接的空闲时间大于180000毫秒时，这些空闲超时的连接会被关闭，直到超时的空闲连接数达到 minimum-idle的值
      connection-test-query: select 1 # 测试连接是否可用的query 语句 在oracle是 select 1 from dual
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 4000
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        # 这里在IDEA中显示红色错误，不用管，因为org.springframework.boot.autoconfigure.data.redis.RedisProperties.Pool.setMaxWait(Duration maxWait)
        # 方法参数是Duration，IDEA无法识别，但是会自动注入成功
        max-wait: 2000 # 当连接池耗尽时， 抛出异常之前，连接分配被阻塞的时间，也就是连接池满后最长等待时间，负值表示无限期等待
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  # 别名前缀,配置类名就不用写全称了
  # type-aliases-package: com.zoctan.seedling.entity
  # mapper 映射文件的位置
  mapper-locations: classpath:mapper/*.xml

mapper:
  # 多个接口时逗号隔开
  mappers: com.min.seed.core.mapper.Mapper
  # insert 和 update 中，判断字符串类型 != ''
  not-empty: false
  # 取回主键的方式
  identity: MYSQL

# 分页插件
# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  # pageSize=0 时查出所有结果，相当于没分页
  page-size-zero: true
  # 数据库方言
  helperDialect: mysql
  # 分页合理化
  # pageNum <= 0 时会查询第一页
  # pageNum > pages（超过总数时），会查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true

#微信token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（单位分钟）一天 1400
  expireTime: 8400


# 日志
logging:
  #  # 以文件方式记录日志
  #  file: seedling.log
  #  # 设置目录
  #  path: /var/log
  level:
    com.min.seed.dao: debug


config:
  username: minych
  password: 123
